/**
 * Created by jzj on 2018/12/24.
 */
'use strict'

export const en = {
  file: 'File',
  open: 'Open',
  openRecent: 'Open Recent',
  clearRecent: 'Clear',
  save: 'Save',
  publish: 'Publish',
  language: 'Language',
  settings: 'Settings',
  edit: 'Edit',
  undo: 'Undo',
  redo: 'Redo',
  cut: 'Cut',
  copy: 'Copy',
  paste: 'Paste',
  selectAll: 'Select All',
  view: 'View',
  reload: 'Reload',
  toggleFullScreen: 'Toggle Full Screen',
  toggleDevTools: 'Toggle Developer Tools',
  window: 'Window',
  minimize: 'Minimize',
  close: 'Close',
  help: 'Help',
  learnMore: 'Learn More',
  openWelcomePage: 'Open Welcome Page',
  viewSampleFile: 'View Sample File',
  about: 'About ',
  services: 'Services',
  hide: 'Hide ',
  hideOthers: 'Hide Others',
  showAll: 'Show All',
  quit: 'Quit',
  bringAllToFront: 'Bring All to Front'
}

export const zh = {
  file: '文件',
  open: '打开',
  openRecent: '打开最近使用的',
  clearRecent: '清除',
  save: '保存',
  publish: '发布',
  language: 'Language',
  settings: '设置',
  edit: '编辑',
  undo: '撤销',
  redo: '重做',
  cut: '剪切',
  copy: '复制',
  paste: '粘贴',
  selectAll: '全选',
  view: '显示',
  reload: '重新加载',
  toggleFullScreen: '切换全屏',
  toggleDevTools: '切换开发者工具',
  window: '窗口',
  minimize: '最小化',
  close: '关闭',
  help: '帮助',
  learnMore: '了解更多',
  openWelcomePage: '打开欢迎页',
  viewSampleFile: '查看示例文档',
  about: '关于',
  services: '服务',
  hide: '隐藏',
  hideOthers: '隐藏其他',
  showAll: '显示全部',
  quit: '退出',
  bringAllToFront: '前置全部窗口'
}
